### ISSUE TITLE
buffer not free()-ed

### ISSUE THREAD

**Issue by VictorVictini** [VictorVictini/CS210Shell#18]
In stage 1 the buffer is malloc-ed but not freed after, free it

**Comment by n8han11** [comment]
Created a branch with the free() function added.

**Comment by VictorVictini** [comment]
neat, I'll check it out but should be good since it's a simple fix

**Comment by Deadly-Pigg** [comment]
there's a problem with simply doing this; it causes the result to output weird characters 'p{☻' on the first input of the shell (this isn't an error later on). We can push this, but it'll develop another issue we'll have to fix later.

This also has the added effect of making the console completely unusable if you try to make a string of length > 512 the first input.
