### ISSUE TITLE
Regarding how arguments are parsed in the shell

### ISSUE THREAD

**Issue by Deadly-Pigg** [VictorVictini/CS210Shell#31]
I've noticed that whilst I was coding stage 4, due to how the arguments are parsed, we cannot access files which contain a token in their names (and it just treats it like 2 or more seperate arguments). 

This is an error with stage 1 that we should resolve sooner or later.

**Comment by mohfez** [comment]
damn

**Comment by Deadly-Pigg** [comment]
Additional info: once stage 1 is fixed to allow for directories with spaces in them, may need to fix stage 4 and 3 to also account for such.

**Comment by Deadly-Pigg** [comment]
actually, scrap that. There only needs to be changes done to stage 1 from my point of view.

**Comment by mohfez** [comment]
stage 3 setpath also needs this

**Comment by Deadly-Pigg** [comment]
unnecessary issue
