### ISSUE TITLE
"No such file or directory" message

### ISSUE THREAD

**Issue by n8han11** [VictorVictini/CS210Shell#8]
Note: I'm currently unsure of how to resolve the "No such file or directory" message that pops up whenever I enter something that isn't an external command (could someone else take a look at the code and determine whether it's a problem with stage 1 or stage 2?)  Otherwise, it works fine enough and hopefully doesn't require too many tweaks.

**Comment by VictorVictini** [comment]
Shouldn't be an issue considering code is near-identical to code provided by lecturer on Mattermost
